name: Output event details on issues

on: issues

jobs:
  output:
    name: output event details in shell via echo
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
