name: Lint, Test and Deploy on push

on: push

jobs:
  build:
    name: run the lint, test and build scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run the lint script
        uses: npm lint

      - name: Run the test script
        uses: npm test

      - name: Run the build script
        uses: npm build
